version: "3.4"
services:
  postgres:
    image: postgres:12.4
    restart: always
    volumes:
      - ./db/init-table.sql:/docker-entrypoint-initdb.d/init-tables.sql
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - fbk-network
      
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - fbk-network
  
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - fbk-network

networks:
  fbk-network:
